"""Thumbnail generation service: Gemini analysis → Flow background → Pillow composition."""

import json
import logging
import random
import re
import uuid
from pathlib import Path

import httpx

from app.core.sse import sse_manager
from app.models.thumbnail import GeminiAnalysis, ThumbnailMode, ThumbnailRequest, ThumbnailStatus, VariantInfo
from app.services import project_service
from app.services.forge_bridge import bridge
from app.services.prompt_generation import repair_json

logger = logging.getLogger(__name__)

# ─── Constants ────────────────────────────────────────────────

THUMBNAIL_WIDTH = 1280
THUMBNAIL_HEIGHT = 720
THUMBNAIL_DIR_NAME = "thumbnail"
THUMBNAIL_FRAGMENT_ID = 9999  # Synthetic fragment ID for thumbnail dispatch


# ─── Prompt Builder ────────────────────────────────────────────


def _detect_language(project_dir: Path | None = None) -> str:
    if project_dir and isinstance(project_dir, str):
        project_dir = Path(project_dir)
    if project_dir:
        for candidate in (project_dir / "audio" / "script.json", project_dir / "script.json"):
            if candidate.exists():
                try:
                    data = json.loads(candidate.read_text(encoding="utf-8"))
                    code = data[0].get("language_code") if isinstance(data, list) else data.get("language_code")
                    if code and isinstance(code, str):
                        code = code.strip().lower()
                        if re.fullmatch(r"[a-z]{2,3}", code):
                            return code
                except Exception:
                    pass
    return "auto"


def _text_language_instruction(language: str) -> str:
    if language == "auto":
        return "in the SAME language as the script/video text (detect it from the script)"
    return f"in {language}"


# Fallback hook text used only when Gemini returns an empty recommended_text.
# Kept language-aware so an English video never shows Spanish fallback copy.
_FALLBACK_HOOK_TEXT = {
    "en": "Watch this!",
    "es": "¡Mira esto!",
    "pt": "Assista!",
    "fr": "Regardez !",
    "de": "Schau dir das an!",
    "it": "Guarda!",
}


def _fallback_hook_text(language: str) -> str:
    if language in _FALLBACK_HOOK_TEXT:
        return _FALLBACK_HOOK_TEXT[language]
    return "Watch this!"


def _build_thumbnail_analysis_prompt(
    script: str,
    mode: ThumbnailMode,
    variant_count: int,
    language: str = "auto",
) -> str:
    """Build a structured prompt for Gemini to analyze a script for thumbnail design.

    Instructs Gemini to return valid JSON with specific fields for YouTube-optimized
    thumbnail analysis. The text will be generated by Flow as part of the image.
    """
    language_instruction = _text_language_instruction(language)
    script_header = f"Given the script (written in {language}) below" if language != "auto" else "Given the script below"

    variant_instruction = ""
    if mode == ThumbnailMode.AB_TESTING:
        variant_instruction = (
            f'\n- "variant_suggestions": array of exactly {variant_count} variants, each with:\n'
            f'  - "hook_text": 3-4 word hook {language_instruction} (emotional, different angle per variant)\n'
            '  - "color_accent": "#hex" high-contrast accent color\n'
            '  - "text_position": lower_third | centered | top_aligned\n'
            '  - "background_image_hint": COMPLETELY DIFFERENT thumbnail background for this variant. '
            "Each variant MUST have a unique background image hint with different scene, colors, "
            "and composition. Think of each as a standalone YouTube thumbnail.\n"
            '  - "composition": lower_third | centered | rule_of_thirds | top_aligned'
        )

    fields = (
        '- "primary_subject": the main visual subject for the thumbnail\n'
        '- "mood_emotion": the dominant emotion or mood\n'
        '- "recommended_colors": {{ "background": "#hex", "text": "#hex", "accent": "#hex" }}\n'
        f'- "recommended_text": 3-4 word hook {language_instruction} (this text will be generated by Flow as part of the image)\n'
        '- "composition": one of: lower_third, centered, rule_of_thirds, top_aligned\n'
        '- "background_image_hint": detailed YouTube thumbnail description for AI image generation. '
        "This is NOT a video scene — it is a standalone thumbnail image. "
        "Include: visual subject, lighting, colors, mood, composition, AND the text to display. "
        "Make it bold, dramatic, high-contrast — designed to get clicks on YouTube. "
        f"The text must be {language_instruction} and will be generated by the image AI as part of the visual."
    )
    if variant_instruction:
        fields += variant_instruction

    return (
        f"You are a YouTube thumbnail designer. {script_header}, "
        "output ONLY a JSON object — nothing else. No explanations, no markdown, no code fences.\n\n"
        "IMPORTANT: Design THUMBNAILS, not video scenes. Each thumbnail must be a standalone "
        "image designed to maximize click-through rate on YouTube. The image AI will generate "
        "the complete thumbnail including text as part of the visual.\n\n"
        "FIELDS (fill with real values based on the script):\n"
        f"{fields}\n"
        "RULES:\n"
        f"- recommended_text: 3-4 words {language_instruction}, high-impact emotional hook. This text will be "
        f"generated by the image AI as part of the thumbnail — it must be {language_instruction}.\n"
        "- recommended_colors: high contrast, bright accents for YouTube (dark backgrounds work best).\n"
        "- background_image_hint: This is the MOST IMPORTANT field. Describe a complete visual "
        "composition for the thumbnail. Include: subject, lighting, colors, mood, style, AND the "
        "text to display. Each variant MUST have a DIFFERENT background. Think dramatic, bold, click-worthy.\n"
        "- composition: lower_third is most common for YouTube.\n"
        "- Remember: thumbnail is viewed at 168x94px on mobile — bold, simple, readable.\n"
        f"- ALL text must be {language_instruction}, with proper accents and punctuation for that language.\n"
        "- The text will be generated by the image AI — describe how it should look in background_image_hint.\n\n"
        f"SCRIPT:\n{script}"
    )


# ─── Gemini Analysis ──────────────────────────────────────────


def _extract_json_block(text: str) -> str:
    """Extract the first JSON object ``{…}`` block from arbitrary text.

    Strips markdown fences, preamble text, trailing commentary, and
    normalises common Gemini quirks (unquoted keys, unquoted short
    string values) so ``json.loads`` or ``repair_json`` can work.
    """
    import re
    candidate = text.strip()
    # Remove markdown fences first
    candidate = re.sub(r"^```(?:json)?\s*\n?", "", candidate, flags=re.IGNORECASE)
    candidate = re.sub(r"\s*```\s*$", "", candidate)
    candidate = candidate.strip()

    # Find the outermost { … } pair
    start = candidate.find("{")
    if start == -1:
        return candidate
    depth = 0
    end = -1
    for i in range(start, len(candidate)):
        ch = candidate[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
    block = candidate[start:end] if end > start else candidate

    # --- Pre-normalisation for common Gemini output quirks ---
    # Quote unquoted object keys (``key:`` → ``"key":``).
    # Matches positions after `{` or `,` (possibly with whitespace).
    block = re.sub(
        r'(?<=[{,])\s*([A-Za-z_]\w*)\s*:',
        r'"\1":',
        block,
    )
    # Quote unquoted single-word string values (``"key": value`` → ``"key": "value"``).
    # Leaves literal tokens (true/false/null/numbers) untouched.
    def _quote_val(m: re.Match) -> str:
        k = m.group(1)
        v = m.group(2)
        delim = m.group(3) or ''
        if re.match(r'^(true|false|null|\d+\.?\d*)$', v, re.IGNORECASE):
            return f'"{k}": {v}{delim}'
        if v.startswith('"'):
            return f'"{k}": {v}{delim}'  # already quoted
        return f'"{k}": "{v}"{delim}'
    block = re.sub(
        r'"([A-Za-z_]\w*)":\s*([A-Za-záéíóúüñ¿¡][A-Za-záéíóúüñ¿¡\w]*?)([,\s\}\]]|$)',
        _quote_val,
        block,
    )
    return block


def _parse_analysis_json(raw_text: str) -> GeminiAnalysis | None:
    """Parse Gemini's response into GeminiAnalysis with json_repair fallback."""
    trimmed = _extract_json_block(raw_text)

    try:
        data = json.loads(trimmed)
    except (json.JSONDecodeError, ValueError):
        logger.info("Gemini JSON parse failed, attempting repair...")
        repaired = repair_json(trimmed)
        try:
            data = json.loads(repaired)
        except (json.JSONDecodeError, ValueError) as e:
            logger.error("Gemini JSON repair also failed: %s | raw=%.200s", e, trimmed[:200])
            return None

    # Normalize field names (handle case differences, underscores vs spaces)
    normalized = {}
    for k, v in data.items():
        nk = k.strip().lower().replace(" ", "_").replace("-", "_")
        normalized[nk] = v

    return GeminiAnalysis(
        primary_subject=str(normalized.get("primary_subject", "")),
        mood_emotion=str(normalized.get("mood_emotion", "")),
        recommended_colors=normalized.get("recommended_colors", {}),
        recommended_text=str(normalized.get("recommended_text", "")),
        composition=str(normalized.get("composition", "lower_third")),
        background_image_hint=str(normalized.get("background_image_hint", "")),
        variant_suggestions=normalized.get("variant_suggestions", None),
    )


async def analyze_script(
    project_id: str,
    script: str,
    mode: ThumbnailMode,
    variant_count: int,
    language: str = "auto",
) -> GeminiAnalysis:
    """Send script to Gemini Web and return structured thumbnail analysis."""
    from app.services.gemini_cookie_store import cookie_store
    from app.services.gemini_web import GeminiWebClient

    profiles = cookie_store.get_authenticated()
    if not profiles:
        raise RuntimeError(
            "Gemini Web: no authenticated profiles. "
            "Install the Chrome extension and log into gemini.google.com first."
        )

    profile = profiles[0]
    psid = profile.get("psid", "")
    psidts = profile.get("psidts", "")

    client = GeminiWebClient(psid, psidts)
    prompt = _build_thumbnail_analysis_prompt(script, mode, variant_count, language)

    logger.info(
        "[THUMBNAIL] Analyzing script for project=%s mode=%s variants=%d",
        project_id, mode.value, variant_count,
    )
    logger.debug("[THUMBNAIL] Prompt (first 300 chars): %.300s", prompt)

    system_prompt = (
        "You are a JSON-only API. Always respond with ONLY valid JSON. "
        "Never include explanations, descriptions, markdown fences, or any text outside the JSON object. "
        "Start your response with { and end with }."
    )
    try:
        raw = client.chat(prompt, system_prompt=system_prompt)
    except Exception as e:
        raise RuntimeError(f"Gemini Web analysis failed: {e}") from e

    logger.info("[THUMBNAIL] Gemini raw response: len=%d preview=%.300s", len(raw), raw[:300])

    analysis = _parse_analysis_json(raw)
    if not analysis:
        # Dump full response to debug file for inspection
        import datetime, tempfile
        debug_file = Path(tempfile.gettempdir()) / f"gemini_thumbnail_debug_{project_id}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        try:
            debug_file.write_text(
                f"=== PROMPT ===\n{prompt}\n\n=== RAW RESPONSE ({len(raw)} chars) ===\n{raw}\n",
                encoding="utf-8",
            )
            logger.error("[THUMBNAIL] Raw response dumped to: %s", debug_file)
        except Exception:
            logger.error("[THUMBNAIL] Full raw response (could not write to file): %s", raw)
        raise RuntimeError(
            f"Failed to parse Gemini analysis response (raw preview: {raw[:200]!r})"
        )

    logger.info(
        "[THUMBNAIL] Analysis complete: subject=%s mood=%s text=%s",
        analysis.primary_subject, analysis.mood_emotion, analysis.recommended_text,
    )
    return analysis


# ─── Background Download ──────────────────────────────────────


async def _download_background(fife_url: str, output_path: Path) -> bool:
    """Download background image from Flow fifeUrl to local path."""
    try:
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.get(fife_url)
            resp.raise_for_status()
            output_path.write_bytes(resp.content)
            logger.info("[THUMBNAIL] Background downloaded: %s (%d bytes)", output_path.name, len(resp.content))
            return True
    except Exception as e:
        logger.error("[THUMBNAIL] Background download failed: %s", e)
        return False


# ─── Pillow Composition ──────────────────────────────────────


def compose_thumbnail(
    project_dir: str,
    analysis: GeminiAnalysis,
    background_path: str | None,
    output_path: str,
) -> bool:
    """Post-process thumbnail: resize and apply subtle vignette.

    Text is NOT overlaid here — it is generated by Flow as part of the image.
    This function only handles resize and visual polish.

    Args:
        project_dir: Project base directory.
        analysis: GeminiAnalysis with color and text recommendations.
        background_path: Path to background image (or None for gradient fallback).
        output_path: Where to save the composed PNG.

    Returns:
        True on success, False on failure.
    """
    from PIL import Image, ImageDraw

    try:
        # ── Step 1: Load or create background ──
        if background_path and Path(background_path).exists():
            with Image.open(background_path) as _bg:
                bg = _bg.convert("RGB")
            bg = bg.resize((THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT), Image.LANCZOS)
        else:
            # Create gradient fallback background
            colors = analysis.recommended_colors
            bg_color = colors.get("background", "#1a1a2e")
            accent = colors.get("accent", "#e94560")
            bg = _create_gradient_background(bg_color, accent)

        # ── Step 2: Apply subtle vignette for depth ──
        overlay = Image.new("RGBA", bg.size, (0, 0, 0, 0))
        draw_ov = ImageDraw.Draw(overlay)
        for y in range(THUMBNAIL_HEIGHT):
            for x in range(THUMBNAIL_WIDTH):
                dx = (x - THUMBNAIL_WIDTH / 2) / (THUMBNAIL_WIDTH / 2)
                dy = (y - THUMBNAIL_HEIGHT / 2) / (THUMBNAIL_HEIGHT / 2)
                dist = min(1.0, (dx * dx + dy * dy) ** 0.5)
                alpha = int(dist * 50)
                draw_ov.point((x, y), fill=(0, 0, 0, alpha))
        bg = Image.alpha_composite(bg.convert("RGBA"), overlay).convert("RGB")

        # ── Step 3: Save ──
        bg.save(output_path, "PNG", quality=95)
        logger.info("[THUMBNAIL] Composed and saved: %s", output_path)
        return True

    except Exception as e:
        logger.error("[THUMBNAIL] Composition failed: %s", e)
        return False


def _create_gradient_background(bg_color: str, accent_color: str) -> "Image":
    """Create a gradient background as fallback when no Flow image is available."""
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (THUMBNAIL_WIDTH, THUMBNAIL_HEIGHT))
    draw = ImageDraw.Draw(img)

    # Parse hex colors
    def hex_to_rgb(h: str) -> tuple:
        h = h.lstrip("#")
        if len(h) == 3:
            h = "".join(c * 2 for c in h)
        if len(h) != 6:
            return (30, 30, 50)
        return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

    bg_rgb = hex_to_rgb(bg_color)
    ac_rgb = hex_to_rgb(accent_color)

    # Draw a smooth vertical gradient
    for y in range(THUMBNAIL_HEIGHT):
        ratio = y / THUMBNAIL_HEIGHT
        r = int(bg_rgb[0] * (1 - ratio) + ac_rgb[0] * ratio)
        g = int(bg_rgb[1] * (1 - ratio) + ac_rgb[1] * ratio)
        b = int(bg_rgb[2] * (1 - ratio) + ac_rgb[2] * ratio)
        draw.line([(0, y), (THUMBNAIL_WIDTH, y)], fill=(r, g, b))

    return img


# ─── Variant Generation ──────────────────────────────────────


async def _generate_variants(
    project_id: str,
    project_dir: str,
    analysis: GeminiAnalysis,
    count: int,
    language: str = "auto",
) -> list[str]:
    """Create variant thumbnails for A/B testing with unique backgrounds per variant.

    Each variant gets:
    - Its own generated background via Flow (different prompt per variant)
    - Different text hook, color accent, and composition
    - A completely distinct visual appearance

    Returns:
        List of paths to generated variant PNGs.
    """
    output_paths: list[str] = []
    thumb_dir = Path(project_dir) / THUMBNAIL_DIR_NAME
    thumb_dir.mkdir(parents=True, exist_ok=True)

    variants = analysis.variant_suggestions or []
    if not variants:
        # Auto-generate variants if Gemini didn't provide suggestions
        for i in range(count):
            variants.append({
                "hook_text": analysis.recommended_text,
                "color_accent": analysis.recommended_colors.get("accent", "#FF4444"),
                "text_position": ["lower_third", "centered", "top_aligned"][i % 3],
                "background_image_hint": analysis.background_image_hint,
            })

    for i, variant in enumerate(variants[:count]):
        hook = variant.get("hook_text", analysis.recommended_text)
        accent = variant.get("color_accent", analysis.recommended_colors.get("accent", "#FF4444"))
        position = variant.get("text_position", analysis.composition or "lower_third")
        variant_hint = variant.get("background_image_hint", analysis.background_image_hint)

        # ── Generate unique thumbnail for this variant ──
        bg_path: str | None = None
        prompt = variant_hint or f"{analysis.primary_subject}, {analysis.mood_emotion}, dramatic YouTube thumbnail background, high contrast, cinematic lighting"
        # Include text in the prompt so Flow generates it as part of the image
        prompt = f'{prompt}. The image must include the text "{hook}" in large, bold, stylized letters as the main visual element. Text must be {_text_language_instruction(language)}.'
        try:
            fife_url = await bridge.dispatch_thumbnail(project_id, prompt)
            if fife_url:
                bg_output = thumb_dir / f"background_v{i + 1}.png"
                downloaded = await _download_background(fife_url, bg_output)
                if downloaded:
                    bg_path = str(bg_output)
                    logger.info("[THUMBNAIL] Variant %d thumbnail generated: %s", i + 1, bg_path)
        except Exception as e:
            logger.warning("[THUMBNAIL] Variant %d thumbnail generation failed, using gradient: %s", i + 1, e)

        # ── Create variant analysis with unique colors ──
        variant_analysis = GeminiAnalysis(
            primary_subject=analysis.primary_subject,
            mood_emotion=analysis.mood_emotion,
            recommended_colors={
                "background": analysis.recommended_colors.get("background", "#1a1a2e"),
                "text": analysis.recommended_colors.get("text", "#FFFFFF"),
                "accent": accent,
            },
            recommended_text=hook,
            composition=position,
            background_image_hint=variant_hint,
        )

        variant_path = str(thumb_dir / f"thumbnail_v{i + 1}.png")
        ok = compose_thumbnail(project_dir, variant_analysis, bg_path, variant_path)
        if ok:
            output_paths.append(variant_path)
            logger.info("[THUMBNAIL] Variant %d saved: %s", i + 1, variant_path)

    return output_paths


# ─── Main Orchestrator ───────────────────────────────────────


async def generate_thumbnail(
    project_id: str,
    request: ThumbnailRequest,
) -> list[str]:
    """Orchestrate the full thumbnail generation pipeline.

    Steps:
    1. Analyze script via Gemini → structured analysis (text, colors, background hint)
    2. Generate thumbnail via Flow dispatch — Flow generates the COMPLETE image including text
    3. Post-process with Pillow (resize + vignette only, NO text overlay)
    4. Generate A/B variants if requested (each with its own unique background and text)

    Text is generated by Flow as part of the image — Pillow does NOT overlay text.

    Returns:
        List of output thumbnail paths.
    """
    project = await project_service.get_project(project_id)
    if not project:
        raise ValueError(f"Project '{project_id}' not found")

    project_dir = project.base_dir
    thumb_dir = Path(project_dir) / THUMBNAIL_DIR_NAME
    thumb_dir.mkdir(parents=True, exist_ok=True)

    language = _detect_language(project_dir)

    # ── Step 1: Analyze script ──
    await sse_manager.emit(project_id, "thumbnail_progress", {
        "status": "analyzing", "progress": 0.1,
        "message": "Analyzing script with Gemini...",
    })

    analysis = await analyze_script(
        project_id, request.script, request.mode, request.variant_count, language,
    )

    # ── Step 2: Generate background for main thumbnail ──
    await sse_manager.emit(project_id, "thumbnail_progress", {
        "status": "generating", "progress": 0.3,
        "message": "Generating thumbnail...",
    })

    background_path: str | None = None

    # Option A: Use existing scene image as background (only if explicitly requested)
    if request.use_existing_scene:
        scene_images = sorted(Path(project_dir).glob("imagenes/escena_*.png"))
        if scene_images:
            background_path = str(scene_images[-1])
            logger.info("[THUMBNAIL] Using existing scene as background: %s", background_path)

    # Option B: Generate thumbnail via Flow dispatch (default)
    if not background_path:
        text = analysis.recommended_text or _fallback_hook_text(language)
        prompt = analysis.background_image_hint
        if not prompt:
            prompt = f"{analysis.primary_subject}, {analysis.mood_emotion}, dramatic YouTube thumbnail background, high contrast, cinematic lighting, bold colors"
        # Include text in the prompt so Flow generates it as part of the image
        prompt = f'{prompt}. The image must include the text "{text}" in large, bold, stylized letters as the main visual element. Text must be {_text_language_instruction(language)}.'
        fife_url = await bridge.dispatch_thumbnail(project_id, prompt)
        if fife_url:
            bg_output = thumb_dir / "background.png"
            downloaded = await _download_background(fife_url, bg_output)
            if downloaded:
                background_path = str(bg_output)

    # ── Step 3: Post-process main thumbnail ──
    await sse_manager.emit(project_id, "thumbnail_progress", {
        "status": "composing", "progress": 0.6,
        "message": "Post-processing thumbnail...",
    })

    main_output = str(thumb_dir / "thumbnail.png")
    ok = compose_thumbnail(project_dir, analysis, background_path, main_output)
    output_paths: list[str] = []
    if ok:
        output_paths.append(main_output)

    # ── Step 4: Generate A/B variants (each with its own background) ──
    if request.mode == ThumbnailMode.AB_TESTING and ok:
        await sse_manager.emit(project_id, "thumbnail_progress", {
            "status": "generating_variants", "progress": 0.7,
            "message": f"Generating {request.variant_count} A/B test variants...",
        })
        variants = await _generate_variants(
            project_id, project_dir, analysis, request.variant_count, language,
        )
        output_paths.extend(variants)

    # ── Update project metadata ──
    thumbnail_paths = [str(Path(p).relative_to(project_dir)) for p in output_paths]
    try:
        await project_service.update_project_meta(project_id, {
            "files": {"thumbnail": thumbnail_paths[0] if thumbnail_paths else ""},
        })
    except Exception as e:
        logger.warning("[THUMBNAIL] Failed to update project meta: %s", e)

    # ── Emit completion ──
    variants_info = [
        VariantInfo(variant=i, url=f"/api/projects/{project_id}/thumbnails/file/{Path(p).name}", seed=random.randint(1, 999999))
        for i, p in enumerate(output_paths)
    ]
    await sse_manager.emit(project_id, "thumbnail_complete", {
        "variants": [v.model_dump() for v in variants_info],
    })

    logger.info(
        "[THUMBNAIL] Generation complete: %d thumbnail(s) for project=%s",
        len(output_paths), project_id,
    )
    return output_paths
